export const NORMAL_PLACEHOLDERS = [
  "what are you working on?",
  "how can i help you today?",
  "ask me anything...",
  "what's on your mind?",
  "ready when you are",
  "what would you like to explore?",
  "enter your message to continue...",
  "what do you need help with?",
  "let's solve something together",
  "shoot your shot",
  "i'm all ears",
  "what's the task at hand?",
  "fire away",
  "what are we building today?",
]

export const GENZ_PLACEHOLDERS = [
  "drop your thoughts bestie",
  "spill the tea or write some code",
  "tell me what's cooking",
  "vibe check: what do you need?",
  "no thoughts just vibes... and prompts",
  "let's get this bread (of knowledge)",
  "main character energy activated",
  "type something iconic",
  "what's the sitch?",
  "go ahead, i'm listening",
  "rizz me with your ideas",
  "ayo what's the mission?",
  "unleash your brainrot",
  "slay the day, one prompt at a time",
  "ratio me with your best question",
  "it's giving curious",
  "lowkey need your hot take",
  "hit me with that sigma grindset",
  "respectfully, what's on your mind?",
  "yeet your ideas into the void",
  "based take incoming?",
  "pop off, i'm ready",
  "fr fr, what do you need?",
  "slaps keyboard aggressively* go on...",
  "tell me something that slaps",
  "delulu is the solulu, ask away",
  "catch me outside, howbow dah? (with ideas)",
  "hold my avocado, let's think",
  "quiet quitting? not on my watch",
  "touch grass, then tell me about it",
  "rent free in your head? tell me more",
  "skibidi toilet? no. skibidi thoughts? yes.",
  "gyatt-level curiosity detected",
  "mewing over here waiting for your prompt",
  "fanum tax me with your best question",
  "only in ohio would you not ask something",
  "looksmaxxing your ideas rn",
  "rizzler mode: activated. drop the question.",
  "sigma grindset requires sigma questions",
  "what's the ick? let's fix it.",
  "bussin' ideas only, no cap",
  "ong tell me what's good",
  "sus if you don't type something",
  "sheesh, that's a clean empty state",
  "npc behavior is not asking questions",
  "beta male detected... just kidding, ask away",
  "giga chad energy starts with a prompt",
  "edging closer to an answer... type something",
  "iykyk, but i don't. explain it to me.",
  "big yikes if you leave me hanging",
  "small brain: silence. galaxy brain: this prompt.",
  "poggers! now what's the question?",
  "monkas if you don't know what to ask",
  "pepehands waiting for your input",
  "kek. now seriously, what's up?",
  "cringe is not asking. based is typing.",
  "understood the assignment? now execute it.",
  "living rent free in my ram, tell me more",
  "vibe shift incoming, initiate prompt",
  "core memory unlocked: your next question",
  "aesthetic empty state, now make it iconic",
  "hypebeast of knowledge waiting for you",
  "stan this conversation, start it",
  "tea is hot, questions are hotter",
  "bop or flop? let me judge your idea",
  "slay the prompt, queen/king/non-binary royalty",
  "era: curious. mood: inquisitive. prompt: pending.",
  "gaslight, gatekeep, girlboss... but first, prompt",
  "yassify your thoughts and drop them here",
  "unalive my boredom with a question",
  "sending you a vibe transmission... receive my prompt",
  "cw: extreme curiosity. proceed with question.",
  "manifesting your next message into existence",
  "plot twist: you actually type something profound",
  "to be fair, you need a very high iq to ask me things",
  "doomscrolling break? ask me something instead",
  "parasocial relationship with ai starts now",
  "clout chasing? chase knowledge instead, bestie",
  "no cap, i'm the goat at answering. test me.",
  "throwing hands with ignorance, help me win",
  "devious lick: stealing your unanswered questions",
  "ate and left no crumbs? now leave a prompt.",
  "understood the assignment? good. now execute.",
  "main character doesn't ghost the ai. type.",
  "caught in 4k not asking anything. redeem yourself.",
  "fumbled the bag? nah, fumble a prompt instead",
]
