name: Setup Node and install npm dependencies
description: Setup Node.js with npm cache and install dependencies with npm ci
inputs:
  node-version:
    description: Node.js version to install
    required: false
    default: '20'
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci
