/**
 * Property-based tests for the VirtualDesktopAccessor FFI adapter (`vdaBinding.ts`).
 *
 * These tests inject a fully mocked native surface through the constructor seam
 * ({@link VdaBindingOptions.loader} / {@link VdaBindingOptions.resolveDllPath}),
 * so neither `koffi` nor a real `VirtualDesktopAccessor.dll` is required. The mock
 * module advertises every required export with the exact arity the load-time probe
 * expects, so `load()` resolves to `'available'`; individual native methods then
 * throw arbitrary failures generated by fast-check.
 *
 * The single property here encodes the design's per-call safety guarantee
 * (Req 8.3): once the binding has loaded, no native failure may escape as a raw
 * exception. Every binding method either returns a value or throws a {@link VdaError}
 * with cause `'call-failed'` — never an unwrapped error, and never an unhandled crash.
 */

// Feature: agent-desktop, Property 30: VDA binding never lets native failures escape

import { describe, it, expect } from 'vitest'
import * as fc from 'fast-check'

import { createVdaBinding, VdaError } from './vdaBinding'
import type { VdaNativeModule, VdaWindowInfo } from './vdaBinding'

/**
 * Shared property-test configuration. The seed is fixed so any failure is
 * reproducible. `numRuns` exceeds the required minimum of 100 iterations.
 */
const PROPERTY_TEST_CONFIG = {
  numRuns: 200,
  seed: 0x5eed,
}

/** The native exports this adapter probes and calls, with their expected arity. */
type NativeMethod =
  | 'GetCurrentDesktopNumber'
  | 'GetDesktopCount'
  | 'CreateDesktop'
  | 'RemoveDesktop'
  | 'GoToDesktop'
  | 'MoveWindowToDesktopNumber'
  | 'IsWindowOnDesktopNumber'
  | 'enumerateWindows'

const NATIVE_METHODS: readonly NativeMethod[] = [
  'GetCurrentDesktopNumber',
  'GetDesktopCount',
  'CreateDesktop',
  'RemoveDesktop',
  'GoToDesktop',
  'MoveWindowToDesktopNumber',
  'IsWindowOnDesktopNumber',
  'enumerateWindows',
]

/** How a single native method should behave for a given generated case. */
interface MethodBehavior {
  /** Whether the native call throws on invocation. */
  throws: boolean
  /** Shape of the thrown value (covers non-Error throwables too). */
  kind: 'error' | 'string' | 'number' | 'object' | 'null'
  /** Message/content carried by the thrown value. */
  message: string
}

type ThrowSpec = Record<NativeMethod, MethodBehavior>

/** Build a throwable of the requested shape so we exercise non-Error rejections too. */
function makeThrowable(kind: MethodBehavior['kind'], message: string): unknown {
  switch (kind) {
    case 'error':
      return new Error(message)
    case 'string':
      return message
    case 'number':
      return message.length
    case 'object':
      return { reason: message }
    case 'null':
    default:
      // eslint-disable-next-line no-throw-literal
      return null
  }
}

/**
 * Construct a mock {@link VdaNativeModule}. Every function preserves the exact arity
 * the load-time probe requires (so `load()` reports `'available'`), but throws the
 * generated failure when the corresponding behavior says so.
 */
function makeNative(spec: ThrowSpec): VdaNativeModule {
  const guard = (method: NativeMethod): void => {
    const behavior = spec[method]
    if (behavior.throws) {
      throw makeThrowable(behavior.kind, behavior.message)
    }
  }

  return {
    GetCurrentDesktopNumber: () => {
      guard('GetCurrentDesktopNumber')
      return 0
    },
    GetDesktopCount: () => {
      guard('GetDesktopCount')
      return 3
    },
    CreateDesktop: () => {
      guard('CreateDesktop')
      return 1
    },
    RemoveDesktop: (index: number) => {
      void index
      guard('RemoveDesktop')
    },
    GoToDesktop: (index: number) => {
      void index
      guard('GoToDesktop')
    },
    MoveWindowToDesktopNumber: (hwnd: number, index: number) => {
      void hwnd
      void index
      guard('MoveWindowToDesktopNumber')
    },
    IsWindowOnDesktopNumber: (hwnd: number, index: number) => {
      void hwnd
      void index
      guard('IsWindowOnDesktopNumber')
      return 1
    },
    enumerateWindows: (): VdaWindowInfo[] => {
      guard('enumerateWindows')
      return []
    },
  }
}

/** fast-check arbitrary describing how one native method behaves. */
const methodBehaviorArb: fc.Arbitrary<MethodBehavior> = fc.record({
  throws: fc.boolean(),
  kind: fc.constantFrom('error', 'string', 'number', 'object', 'null'),
  message: fc.string(),
})

/** A behavior spec for every native method. */
const throwSpecArb: fc.Arbitrary<ThrowSpec> = fc.record(
  NATIVE_METHODS.reduce(
    (acc, method) => {
      acc[method] = methodBehaviorArb
      return acc
    },
    {} as Record<NativeMethod, fc.Arbitrary<MethodBehavior>>
  )
) as fc.Arbitrary<ThrowSpec>

describe('VdaBinding native-failure isolation (Property 30)', () => {
  /**
   * Property 30: VDA binding never lets native failures escape.
   *
   * For any combination of native methods that throw (with arbitrary thrown
   * values), after a successful `load()` every binding method either returns a
   * value or throws a `VdaError` with cause `'call-failed'`. No raw native
   * exception escapes and the process never crashes.
   *
   * **Validates: Requirements 8.3**
   */
  it('wraps every native failure in a VdaError(call-failed) and never lets a raw error escape', async () => {
    await fc.assert(
      fc.asyncProperty(
        throwSpecArb,
        fc.integer({ min: -5, max: 1000 }), // hwnd
        fc.integer({ min: -5, max: 1000 }), // index
        async (spec, hwnd, index) => {
          const native = makeNative(spec)
          const binding = createVdaBinding({
            loader: () => native,
            resolveDllPath: () => 'C:/mock/agentDesktop/native/VirtualDesktopAccessor.dll',
          })

          // The mock provides all required exports with correct arity, so the
          // load-time probe must succeed.
          const outcome = await binding.load()
          expect(outcome).toBe('available')
          expect(binding.isAvailable()).toBe(true)

          // Every public method that can reach the native surface.
          const invocations: ReadonlyArray<() => unknown> = [
            () => binding.getCurrentDesktopIndex(),
            () => binding.getDesktopCount(),
            () => binding.createDesktop(),
            () => binding.removeDesktop(index),
            () => binding.goToDesktop(index),
            () => binding.desktopExists(index),
            () => binding.moveWindowToDesktop(hwnd, index),
            () => binding.isWindowOnDesktop(hwnd, index),
            () => binding.enumerateWindows(),
          ]

          for (const invoke of invocations) {
            try {
              // Either it returns a value (acceptable) ...
              invoke()
            } catch (error) {
              // ... or it throws — and the only permitted escaping error type is
              // a VdaError with cause 'call-failed'. A raw/unwrapped error here
              // would fail the property.
              expect(error).toBeInstanceOf(VdaError)
              expect((error as VdaError).cause).toBe('call-failed')
            }
          }

          // dispose() must never throw, even though we never gave the mock a
          // dispose() hook.
          expect(() => binding.dispose()).not.toThrow()
        }
      ),
      PROPERTY_TEST_CONFIG
    )
  })
})
