export const SCREENSHOT_MAX_WIDTH = 1280
export const SCREENSHOT_QUALITY = 'png' as const
export const ACTION_DELAY_MS = 150
export const DEFAULT_SCROLL_AMOUNT = 3
export const MAX_ACTIONS_PER_SESSION = 50
export const APPROVAL_TIMEOUT_MS = 60_000
export const SPOTLIGHT_DURATION_MS = 600
export const SPOTLIGHT_RADIUS = 40
export const KILL_SWITCH_WINDOW_MS = 500
