export const SEARCH_FETCH_TIMEOUT_MS = 20_000
export const SEARCH_EXTRACT_FETCH_TIMEOUT_MS = 30_000
export const SEARCH_MAX_QUERY_LENGTH = 500
export const SEARCH_MAX_RESULTS = 4
export const SEARCH_MAX_EXTRACT_URLS = 20
export const SEARCH_EXTRACT_SNIPPET_LENGTH = 500
