#!/usr/bin/env node
/**
 * Quality ratchet: fails on newly introduced formatting, lint, or dead-code
 * findings while tolerating the documented pre-existing baseline.
 *
 * Usage:
 *   bun scripts/quality-ratchet.mjs            # check against the baseline
 *   bun scripts/quality-ratchet.mjs --update   # regenerate the baseline
 */

import { spawnSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { compareFindings, formatRatchetReport, tallyFindings } from './qualityRatchet.mjs'

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const baselinePath = path.join(repoRoot, 'quality-baseline.json')

/** Runs a command and returns stdout, tolerating a non-zero exit. */
function run(command, args) {
  const result = spawnSync(command, args, {
    cwd: repoRoot,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  })
  if (result.error) {
    throw new Error(`Failed to run ${command} ${args.join(' ')}: ${result.error.message}`)
  }
  return result.stdout ?? ''
}

function toPosix(filePath) {
  return path.relative(repoRoot, path.resolve(repoRoot, filePath)).split(path.sep).join('/')
}

/** Files prettier would rewrite. Finding key is the file path. */
function collectPrettierFindings() {
  const stdout = run('bunx', ['prettier', '--list-different', '.'])
  const files = stdout
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map(toPosix)
  return tallyFindings(files)
}

/** ESLint findings. Finding key is `<file>::<ruleId>`. */
function collectEslintFindings() {
  const stdout = run('bunx', ['eslint', '.', '--format', 'json'])
  const jsonStart = stdout.indexOf('[')
  if (jsonStart === -1) return {}

  /** @type {Array<{filePath: string, messages: Array<{ruleId: string | null}>}>} */
  const results = JSON.parse(stdout.slice(jsonStart))
  const keys = []
  for (const result of results) {
    for (const message of result.messages) {
      keys.push(`${toPosix(result.filePath)}::${message.ruleId ?? 'unknown'}`)
    }
  }
  return tallyFindings(keys)
}

/** Knip findings. Finding key is `<issueType>::<file>::<symbol>`. */
function collectKnipFindings() {
  const stdout = run('bunx', ['knip', '--reporter', 'json'])
  const jsonStart = stdout.indexOf('{')
  if (jsonStart === -1) return {}

  let parsed
  try {
    parsed = JSON.parse(stdout.slice(jsonStart))
  } catch {
    // Knip's JSON reporter emits `{ files: [], issues: [] }`; anything else means
    // the run itself failed, which must not be silently treated as "clean".
    throw new Error(`Could not parse knip JSON output:\n${stdout.slice(0, 2000)}`)
  }

  const keys = []
  for (const file of parsed.files ?? []) {
    keys.push(`files::${toPosix(file)}::`)
  }
  for (const issue of parsed.issues ?? []) {
    const file = toPosix(issue.file ?? '')
    for (const [issueType, entries] of Object.entries(issue)) {
      if (issueType === 'file' || !entries) continue
      const list = Array.isArray(entries) ? entries : [entries]
      for (const entry of list) {
        const symbol =
          typeof entry === 'string' ? entry : (entry?.name ?? entry?.symbol ?? String(entry))
        keys.push(`${issueType}::${file}::${symbol}`)
      }
    }
  }
  return tallyFindings(keys)
}

const CHECKS = [
  { name: 'prettier', collect: collectPrettierFindings },
  { name: 'eslint', collect: collectEslintFindings },
  { name: 'knip', collect: collectKnipFindings },
]

function readBaseline() {
  try {
    const parsed = JSON.parse(readFileSync(baselinePath, 'utf8'))
    return parsed.checks ?? {}
  } catch (error) {
    if (error && error.code === 'ENOENT') return {}
    throw error
  }
}

function main() {
  const shouldUpdate = process.argv.includes('--update')
  const only = process.argv.find((arg) => arg.startsWith('--only='))?.slice('--only='.length)
  const checks = only ? CHECKS.filter((check) => check.name === only) : CHECKS

  if (checks.length === 0) {
    console.error(`Unknown check: ${only}`)
    process.exit(2)
  }

  const collected = {}
  for (const check of checks) {
    process.stderr.write(`Collecting ${check.name} findings...\n`)
    collected[check.name] = check.collect()
  }

  if (shouldUpdate) {
    const existing = readBaseline()
    const merged = { ...existing, ...collected }
    writeFileSync(
      baselinePath,
      `${JSON.stringify(
        {
          $comment:
            'Pre-existing quality debt. Only shrink this file. Generated by "bun run quality:baseline".',
          generatedAt: new Date().toISOString().slice(0, 10),
          checks: merged,
        },
        null,
        2
      )}\n`,
      'utf8'
    )
    const total = Object.values(collected).reduce(
      (sum, findings) => sum + Object.values(findings).reduce((a, b) => a + b, 0),
      0
    )
    console.log(`Wrote ${path.basename(baselinePath)} with ${total} baseline finding(s).`)
    return
  }

  const baseline = readBaseline()
  const results = checks.map((check) =>
    compareFindings(baseline[check.name] ?? {}, collected[check.name], check.name)
  )

  const { ok, report } = formatRatchetReport(results)
  console.log(report)
  process.exit(ok ? 0 : 1)
}

main()
